workspace:
  base: /go
  path: src/github.com/karantin2020/wide-docker

pipeline:
  publish:
    group: dopub
    image: plugins/docker
    repo: node3030/wide
    secrets: [ docker_username, docker_password ]
    tag: [ 'latest', '1.5', '1.5.2' ]
    when:
      branch: master
      event: push
      
  release:
    group: dopub
    image: plugins/docker
    repo: node3030/wide
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_TAG##v}
    when:
      event: tag
